### ISSUE TITLE
"TypeError: Cannot set property 'id' of undefined" randomly being thrown

### ISSUE THREAD

**Issue by PikaDude** [abalabahaha/eris#953]
Hi, I'm occasionally getting the following error after updating from Eris 0.11.0 to Eris 0.13.0, and then 0.13.1. This issue started with Eris 0.13.0 and has persisted to 0.13.1, however I'm not sure if it happened in 0.12.0 as I skipped that version. Seemingly random, the following error is reported between 1-10 consecutive times each time it occurs.

```
TypeError: Cannot set property 'id' of undefined
     at Shard.wsEvent (node_modules/eris/lib/gateway/Shard.js:592:48)
     at Shard.onWSMessage (node_modules/eris/lib/gateway/Shard.js:1904:26)
     at WebSocket.ws.onmessage (node_modules/eris/lib/gateway/Shard.js:1795:33)
     at WebSocket.onMessage (node_modules/eris/node_modules/ws/lib/event-target.js:120:16)
     at WebSocket.emit (events.js:310:20)
     at Receiver.receiverOnMessage (node_modules/eris/node_modules/ws/lib/websocket.js:801:20)
     at Receiver.emit (events.js:310:20)
     at Receiver.dataMessage (node_modules/eris/node_modules/ws/lib/receiver.js:436:14)
     at Receiver.getData (node_modules/eris/node_modules/ws/lib/receiver.js:366:17)
     at Receiver.startLoop (node_modules/eris/node_modules/ws/lib/receiver.js:142:22)
```

While I do utilise eris-sharder, I don't believe it is the cause after checking the source of the error, however I could be wrong.

**Comment by ghost** [comment]
fixed in #952

**Comment by PikaDude** [comment]
Ah, awesome, thanks. 👍 I did try checking to see if this had already been reported, but I wasn't aware of was the cause so I didn't know that that was related lol, sorry for the dupe.

**Comment by TheBabu** [comment]
I'm still getting those errors?
```
[nodemon] starting `node app.js`
events.js:292
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property 'id' of undefined
    at Shard.wsEvent (/home/ariq/Programming/HTML/Discord-Babubot/node_modules/eris/lib/gateway/Shard.js:592:48)
    at Shard.onWSMessage (/home/ariq/Programming/HTML/Discord-Babubot/node_modules/eris/lib/gateway/Shard.js:1904:26)
    at WebSocket.ws.onmessage (/home/ariq/Programming/HTML/Discord-Babubot/node_modules/eris/lib/gateway/Shard.js:1795:33)
    at WebSocket.onMessage (/home/ariq/Programming/HTML/Discord-Babubot/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/home/ariq/Programming/HTML/Discord-Babubot/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/home/ariq/Programming/HTML/Discord-Babubot/node_modules/ws/lib/receiver.js:436:14)
    at Receiver.getData (/home/ariq/Programming/HTML/Discord-Babubot/node_modules/ws/lib/receiver.js:366:17)
    at Receiver.startLoop (/home/ariq/Programming/HTML/Discord-Babubot/node_modules/ws/lib/receiver.js:142:22)
Emitted 'error' event on Client instance at:
    at Shard.emit (/home/ariq/Programming/HTML/Discord-Babubot/node_modules/eris/lib/gateway/Shard.js:2093:26)
    at WebSocket.ws.onmessage (/home/ariq/Programming/HTML/Discord-Babubot/node_modules/eris/lib/gateway/Shard.js:1798:22)
    at WebSocket.onMessage (/home/ariq/Programming/HTML/Discord-Babubot/node_modules/ws/lib/event-target.js:125:16)
    [... lines matching original stack trace ...]
    at Receiver.startLoop (/home/ariq/Programming/HTML/Discord-Babubot/node_modules/ws/lib/receiver.js:142:22)
    at Receiver._write (/home/ariq/Programming/HTML/Discord-Babubot/node_modules/ws/lib/receiver.js:77:10)
[nodemon] app crashed - waiting for file changes before starting...
```
It also seems to be random, I am currently using the npm package.

**Comment by bsian03** [comment]
I take 
>  using the npm package

as you not being on the Dev branch. The fix has not yet been merged to master
